title = "A Demonstration Book"
author = "Ann O'Nymous"
language = "en"
# cover_image = "src/cover.jpg"
# cover_alt = "A silly demonstration book cover"
# cover_title = "Some text to show about the cover"

# Optional: if you want nice URLs like /chapter/...
base_url = "/"

# Optional: EPUB file to copy to assets and offer as download
# epub_file = "src/MyBook.epub"

# Optional: External links to show on the index page
# [[external_link]]
# text = "Read on AO3"
# url = "https://archiveofourown.org/works/12345"
#
# [[external_link]]
# text = "Buy on Amazon"
# url = "https://www.amazon.com/..."

[[chapter]]
title = "Preface"
source = "src/chapters/preface.md"

[[chapter]]
title = "Chapter 1: Wow, A Book!"
source = "src/chapters/chap01.md"

[[chapter]]
title = "Chapter 2: Something Happens"
source = "src/chapters/chap02.md"

[[chapter]]
title = "Chapter 3: The End?"
source = "src/chapters/chap03.md"

[[chapter]]
title = "Afterword"
source = "src/chapters/afterword.md"

